---
- name: Add docker group
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: "{{ deploy_user }}"
    append: yes
    groups: docker

- name: Create docker.service.d directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root

- name: Override systemd conofig
  template:
    src: docker.service.override.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
  notify:
    - systemd reload
    - restart docker

- name: Enable docker service
  systemd:
    name: docker
    enabled: yes
