---
- name: Add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
    filename: docker
    state: present

- name: Install docker
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python-pip
  apt:
    update_cache: yes
    name: "{{ packages }}"
    state: present

- name: Install docker-compose
  pip:
    name: docker-compose
    state: present
