---
- name: Install dependencies
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present
