global:
  slack_api_url: 'https://hooks.slack.com/services/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'
  smtp_from: 'alert@example.com'
  smtp_smarthost: 'smtp.mailtrap.io:2525'
  smtp_auth_username: '7a74292904a936'
  smtp_auth_password: '12f44a3ad43b2f'

route:
  receiver: 'email-and-slack-notifications'

receivers:
- name: 'email-and-slack-notifications'
  slack_configs:
  - channel: '#dmitriy_usachev'
  email_configs:
  - to: 'sjotus@gmail.com'
