---
- name: Create gitlab-runner tmp dir
  file:
    path: /tmp/gitlab-runner
    state: directory

- name: Render compose file
  template:
    src: docker-compose.yml.j2
    dest: /tmp/gitlab-runner/docker-compose.yml

# - name: Run gitlab-runner
#   docker-compose:
#     project_src: /tmp/gitlab-runner
#     state: present
