---
- name: Install Gitlab Runnner
  import_tasks: install.yml

- name: Register runners
  include_tasks: register.yml
  loop: "{{ gitlab_runner_runners }}"
  loop_control:
    index_var: gitlab_runner_index
    loop_var: gitlab_runner
  when: compose.changed
