---
# Monitoring vars
# Networks defined global in compose file.
# For networks that created in other compose use "external: true"
monitoring_networks:
  - prometheus:
      external: false
  - gitlab:
      external: true
# networks used by prometheus container
prometheus_networks:
  - prometheus
  - gitlab

prometheus_scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'
  - job_name: 'crawler-engine'
    metrics_path: /
    static_configs:
      - targets:
          - "{{ stage_address }}:8001"

  - job_name: 'crawler-ui'
    static_configs:
      - targets:
          - "{{ stage_address }}:8000"
