---
prometheus_image: prom/prometheus:v2.13.1
grafana_image: grafana/grafana:5.0.0
prometheus_scrape_interval: '5s'
prometheus_scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'
prometheus_networks:
  - prometheus

grafana_networks:
  - prometheus

monitoring_networks:
  - prometheus:
      external: false
