---
prometheus_image: prom/prometheus:v2.13.1
grafana_image: grafana/grafana:5.0.0
trickster_image: tricksterio/trickster
alertmanager_image: prom/alertmanager:v0.14.0
node-exporter_image: prom/node-exporter:v0.15.2
prometheus_scrape_interval: '5s'
prometheus_scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'
prometheus_networks:
  - prometheus

trickster_networks:
  - prometheus

grafana_networks:
  - prometheus

alertmanager_networks:
  - prometheus

node-exporter_networks:
  - prometheus

monitoring_networks:
  - prometheus:
      external: false
