---
env: stage

# gitlab-runner vars
gitlab_runner_runners:
  - name: "Privileged docker runner"
    executor: docker
    docker_image: "docker:19.03"
    tags:
      - docker
      - linux
      - dind
      - "{{ env }}"
    docker_volumes:
      - "/cache"
    docker_privileged: true
