---
env: stage

# gitlab-runner vars
gitlab_runner_runners:
  - name: "{{ env }} - Privileged docker runner"
    executor: docker
    docker_image: "docker:19.03"
    tags:
      - docker
      - linux
      - dind
      - "{{ env }}"
    docker_volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/cache"
    docker_privileged: true
    wait_for_services_timeout: '45'
