---
# install base software to VM, like python
- name: Check and Install python
  hosts: all
  become: true
  gather_facts: False

  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False

    - name: Remove apt lock file
      file:
        state: absent
        path: "/var/lib/dpkg/lock-frontend"
      become: true

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Remove apt lock file2
      file:
        state: absent
        path: "{{ item }}"
      become: true
      with_items:
        - /var/cache/apt/archives/lock
        - /var/lib/dpkg/lock-frontend

    - name: Install pyhthon dependencies
      vars:
        packages:
          - python-pip
          - python-virtualenv
          - python-setuptools
      apt:
        name: "{{ packages }}"
        update_cache: no
        state: present

    # - name: Install python libraries for use docker with Ansible
    #   pip:
    #     name: docker
    #     state: present
