---
# Waits until remote system is reachable/usable
- name: Waits until remote system is reachable/usable
  gather_facts: no
  hosts: all
  tasks:
    - name: Wait, but only start checking after 30 seconds
      wait_for_connection:
        delay: 30
        sleep: 20
